// Code generated by "stringer -type=TransferStatus"; DO NOT EDIT.

package reflux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusNotStarted-0]
	_ = x[StatusInProgress-1]
	_ = x[StatusCompleted-2]
	_ = x[StatusFailed-3]
}

const _TransferStatus_name = "StatusNotStartedStatusInProgressStatusCompletedStatusFailed"

var _TransferStatus_index = [...]uint8{0, 16, 32, 47, 59}

func (i TransferStatus) String() string {
	if i >= TransferStatus(len(_TransferStatus_index)-1) {
		return "TransferStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransferStatus_name[_TransferStatus_index[i]:_TransferStatus_index[i+1]]
}
